# Generated by Django 5.2.17 on 2026-09-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='机台名称')),
                ('machine_type', models.CharField(max_length=50, verbose_name='机型')),
                ('status', models.CharField(choices=[('running', '生产中'), ('idle', '空闲'), ('maintenance', '维保中')], default='idle', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '机台',
                'verbose_name_plural': '机台',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='纸张名称')),
                ('paper_type', models.CharField(choices=[('coated', '铜版纸'), ('offset', '胶版纸'), ('whiteboard', '白卡纸'), ('kraft', '牛皮纸'), ('special', '特种纸')], max_length=20, verbose_name='纸张类型')),
                ('spec', models.CharField(blank=True, max_length=80, verbose_name='规格(克重/尺寸)')),
                ('stock', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='库存(张)')),
                ('safety_stock', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='安全库存(张)')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='单价(元/张)')),
            ],
            options={
                'verbose_name': '纸张材料',
                'verbose_name_plural': '纸张材料',
                'unique_together': {('name', 'spec')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('product_name', models.CharField(max_length=150, verbose_name='产品名称')),
                ('quantity', models.PositiveIntegerField(verbose_name='印数(份)')),
                ('paper_consumption', models.PositiveIntegerField(default=0, verbose_name='用纸量(张)')),
                ('status', models.CharField(choices=[('pending', '待排产'), ('prepress', '印前中'), ('printing', '印刷中'), ('binding', '装订中'), ('completed', '已完成'), ('rework', '返工中')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_date', models.DateField(verbose_name='下单日期')),
                ('due_date', models.DateField(verbose_name='交货日期')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='factory.customer', verbose_name='客户')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='factory.paper', verbose_name='用纸')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaperTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='类型')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量(张)')),
                ('tx_date', models.DateField(verbose_name='日期')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.order', verbose_name='关联订单')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='factory.paper', verbose_name='纸张')),
            ],
            options={
                'verbose_name': '纸张流水',
                'verbose_name_plural': '纸张流水',
                'ordering': ['-tx_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepress_status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('rework', '返工中')], default='not_started', max_length=20, verbose_name='印前状态')),
                ('prepress_progress', models.PositiveSmallIntegerField(default=0, verbose_name='印前进度%')),
                ('prepress_note', models.CharField(blank=True, max_length=200, verbose_name='印前说明')),
                ('prepress_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='印前完成时间')),
                ('printing_status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('rework', '返工中')], default='not_started', max_length=20, verbose_name='印刷状态')),
                ('printing_progress', models.PositiveSmallIntegerField(default=0, verbose_name='印刷进度%')),
                ('printing_note', models.CharField(blank=True, max_length=200, verbose_name='印刷说明')),
                ('printing_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='印刷完成时间')),
                ('binding_status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('rework', '返工中')], default='not_started', max_length=20, verbose_name='装订状态')),
                ('binding_progress', models.PositiveSmallIntegerField(default=0, verbose_name='装订进度%')),
                ('binding_note', models.CharField(blank=True, max_length=200, verbose_name='装订说明')),
                ('binding_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='装订完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='factory.order')),
            ],
            options={
                'verbose_name': '工序进度',
                'verbose_name_plural': '工序进度',
            },
        ),
        migrations.CreateModel(
            name='ReworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prepress', '印前'), ('printing', '印刷'), ('binding', '装订')], max_length=20, verbose_name='返工工序')),
                ('reason', models.CharField(choices=[('color', '色差'), ('register', '套印不准'), ('scratch', '划伤/脏点'), ('binding', '装订错误'), ('material', '材料问题'), ('other', '其他')], max_length=20, verbose_name='返工原因')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='返工数量(份)')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '返工中'), ('closed', '已闭环')], default='open', max_length=20, verbose_name='处理状态')),
                ('description', models.TextField(blank=True, verbose_name='问题描述')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='责任人')),
                ('found_at', models.DateField(verbose_name='发现日期')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='闭环日期')),
                ('result', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworks', to='factory.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '返工单',
                'verbose_name_plural': '返工单',
                'ordering': ['-found_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('shift', models.CharField(default='白班', max_length=10, verbose_name='班次')),
                ('planned_qty', models.PositiveIntegerField(default=0, verbose_name='计划产量(份)')),
                ('actual_qty', models.PositiveIntegerField(default=0, verbose_name='实际产量(份)')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='factory.machine', verbose_name='机台')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='factory.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '排产计划',
                'verbose_name_plural': '排产计划',
                'ordering': ['planned_date', 'shift', 'id'],
            },
        ),
    ]
