# Generated by Django 5.2.17 on 2026-09-15 12:07

import django.db.models.deletion
import factory.models
from django.db import migrations, models


def migrate_legacy_stock(apps, schema_editor):
    """旧库没有批次概念：为每种纸补建一个“期初批次”，并把历史流水挂到该批次，
    使批次剩余数量与纸张库存一致（仅处理当前批次为空的数据，可安全重复执行）。"""
    Paper = apps.get_model('factory', 'Paper')
    PaperBatch = apps.get_model('factory', 'PaperBatch')
    PaperTransaction = apps.get_model('factory', 'PaperTransaction')

    for paper in Paper.objects.all():
        txs = PaperTransaction.objects.filter(paper=paper)
        if not txs.exists() or PaperBatch.objects.filter(paper=paper).exists():
            continue
        first_date = txs.order_by('tx_date', 'id').first().tx_date
        batch = PaperBatch.objects.create(
            paper=paper, batch_no='QC-LEGACY',
            arrival_date=first_date, expiry_date=None, note='历史库存迁移（原未登记批次）',
        )
        txs.update(batch=batch)


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('arrival_date', models.DateField(default=factory.models.today, verbose_name='到货日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='保质期至')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='factory.paper', verbose_name='纸张')),
            ],
            options={
                'verbose_name': '纸张批次',
                'verbose_name_plural': '纸张批次',
                'ordering': ['arrival_date', 'id'],
                'unique_together': {('paper', 'batch_no')},
            },
        ),
        migrations.AddField(
            model_name='papertransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='factory.paperbatch', verbose_name='批次'),
        ),
        migrations.RunPython(migrate_legacy_stock, migrations.RunPython.noop),
    ]
