# Generated by Django 5.2.17 on 2026-09-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('白班', '白班'), ('夜班', '夜班')], default='白班', max_length=10, verbose_name='班次'),
        ),
        migrations.CreateModel(
            name='MachineShiftCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('白班', '白班'), ('夜班', '夜班')], max_length=10, verbose_name='班次')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='班次产能(份)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_capacities', to='factory.machine', verbose_name='机台')),
            ],
            options={
                'verbose_name': '机台班次产能',
                'verbose_name_plural': '机台班次产能',
                'unique_together': {('machine', 'shift')},
            },
        ),
    ]
