# Generated by Django 5.2.17 on 2026-09-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待排产'), ('prepress', '印前中'), ('printing', '印刷中'), ('binding', '装订中'), ('completed', '待发货'), ('shipped', '已发货'), ('rework', '返工中')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='发货数量(份)')),
                ('ship_date', models.DateField(verbose_name='发货日期')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('tracking_no', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='factory.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '发货记录',
                'verbose_name_plural': '发货记录',
                'ordering': ['ship_date', 'id'],
            },
        ),
    ]
