# Generated by Django 5.2.17 on 2026-09-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次保养日期'),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_cycle_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='保养周期(天)'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='保养日期')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='保养内容/备注')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='保养人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='factory.machine', verbose_name='机台')),
            ],
            options={
                'verbose_name': '保养记录',
                'verbose_name_plural': '保养记录',
                'ordering': ['-maintenance_date', '-id'],
            },
        ),
    ]
