# Generated by Django 5.2.17 on 2026-09-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='生产日期')),
                ('shift', models.CharField(default='白班', max_length=10, verbose_name='班次')),
                ('planned_qty', models.PositiveIntegerField(default=0, verbose_name='计划产量(份)')),
                ('actual_qty', models.PositiveIntegerField(default=0, verbose_name='实际产量(份)')),
                ('abnormal_note', models.TextField(blank=True, verbose_name='异常说明')),
                ('handover_note', models.TextField(blank=True, verbose_name='交接事项')),
                ('duty_officer', models.CharField(blank=True, max_length=50, verbose_name='值班人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='factory.machine', verbose_name='机台')),
            ],
            options={
                'verbose_name': '交接班记录',
                'verbose_name_plural': '交接班记录',
                'ordering': ['-work_date', 'shift', 'machine_id'],
                'unique_together': {('machine', 'work_date', 'shift')},
            },
        ),
    ]
