# Generated by Django 5.2.17 on 2026-09-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkrecord',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='损耗金额(元)'),
        ),
        migrations.AddField(
            model_name='reworkrecord',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reworks', to='factory.machine', verbose_name='返工机台'),
        ),
        migrations.AddField(
            model_name='reworkrecord',
            name='makeup_sheets',
            field=models.PositiveIntegerField(default=0, verbose_name='补投张数(张)'),
        ),
    ]
