# Generated by Django 5.2.17 on 2026-09-15 13:44

from django.db import migrations, models


def strip_handover_notes(apps, schema_editor):
    """清洗历史数据：异常说明/交接事项/值班人去掉首尾空白，
    保证异常判定（按 stripped 内容）对存量记录同样生效"""
    ShiftHandover = apps.get_model('factory', 'ShiftHandover')
    for rec in ShiftHandover.objects.all():
        rec.abnormal_note = (rec.abnormal_note or '').strip()
        rec.handover_note = (rec.handover_note or '').strip()
        rec.duty_officer = (rec.duty_officer or '').strip()
        rec.save(update_fields=['abnormal_note', 'handover_note', 'duty_officer'])


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_shifthandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandover',
            name='source',
            field=models.CharField(choices=[('auto', '自动生成'), ('manual', '手动补录')], default='auto', max_length=10, verbose_name='来源'),
        ),
        migrations.RunPython(strip_handover_notes, migrations.RunPython.noop),
    ]
